name: albocarride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core and Messaging
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1

  # Supabase Flutter SDK for authentication and database
  supabase_flutter: ^2.10.1

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Persistent storage for session management
  shared_preferences: ^2.4.1

  # Secure storage for sensitive data
  flutter_secure_storage: ^9.0.0

  # Network connectivity monitoring
  connectivity_plus: ^5.0.2

  # Image compression for document uploads
  flutter_image_compress: ^2.0.0

  # Image picker for camera/gallery access
  image_picker: ^1.0.4

  # HTTP client for API calls
  http: ^1.2.2

  # Path utilities for file operations
  path: ^1.8.3

  # State management
  provider: ^6.1.1

  # UUID generation
  uuid: ^4.4.0

  # Location services for driver tracking
  geolocator: ^11.0.1

  # Google Maps for Flutter
  google_maps_flutter: ^2.5.0

  # App links for deep linking (Android only) - DISABLED due to cross-drive symlink issues
  # app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter:
  uses-material-design: true

  assets:
    - .env
