// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaXqWdZgxXkjhAsn2TFOXPPUL9xSXbDZw',
    appId: '1:167231435552:web:bc6cf32c6b5d9e8ac99d45',
    messagingSenderId: '167231435552',
    projectId: 'albo-car-ride',
    authDomain: 'albo-car-ride.firebaseapp.com',
    storageBucket: 'albo-car-ride.firebasestorage.app',
    measurementId: 'G-BKKY1DBEJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVL0X5qJptdAB3QHPR_goILFwpEmznhWE',
    appId: '1:167231435552:android:bdaa3b35233929ebc99d45',
    messagingSenderId: '167231435552',
    projectId: 'albo-car-ride',
    storageBucket: 'albo-car-ride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yDezdIVEsT74Ez0-ICTnXMoFhW90C2w',
    appId: '1:167231435552:ios:cfec2ffca18c8e0ec99d45',
    messagingSenderId: '167231435552',
    projectId: 'albo-car-ride',
    storageBucket: 'albo-car-ride.firebasestorage.app',
    iosBundleId: 'com.example.albocarride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yDezdIVEsT74Ez0-ICTnXMoFhW90C2w',
    appId: '1:167231435552:ios:cfec2ffca18c8e0ec99d45',
    messagingSenderId: '167231435552',
    projectId: 'albo-car-ride',
    storageBucket: 'albo-car-ride.firebasestorage.app',
    iosBundleId: 'com.example.albocarride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaXqWdZgxXkjhAsn2TFOXPPUL9xSXbDZw',
    appId: '1:167231435552:web:78814f3c45043e54c99d45',
    messagingSenderId: '167231435552',
    projectId: 'albo-car-ride',
    authDomain: 'albo-car-ride.firebaseapp.com',
    storageBucket: 'albo-car-ride.firebasestorage.app',
    measurementId: 'G-ED1KSL8RJT',
  );
}
