// Mocks generated by Mockito 5.4.6 from annotations
// in albocarride/test/screens/home/book_ride_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i12;

import 'package:albocarride/services/location_service.dart' as _i10;
import 'package:albocarride/services/session_service.dart' as _i11;
import 'package:flutter/material.dart' as _i14;
import 'package:flutter/services.dart' as _i13;
import 'package:http/http.dart' as _i7;
import 'package:logging/logging.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:realtime_client/src/message.dart' as _i9;
import 'package:realtime_client/src/retry_timer.dart' as _i4;
import 'package:supabase/supabase.dart' as _i2;
import 'package:web_socket_channel/web_socket_channel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_9 extends _i1.SmartFake
    implements _i2.GoTrueAdminApi {
  _FakeGoTrueAdminApi_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_10 extends _i1.SmartFake implements _i2.GoTrueMFAApi {
  _FakeGoTrueMFAApi_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_11 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_12 extends _i1.SmartFake implements _i2.OAuthResponse {
  _FakeOAuthResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_13 extends _i1.SmartFake
    implements _i2.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_14 extends _i1.SmartFake
    implements _i2.ResendResponse {
  _FakeResendResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_15 extends _i1.SmartFake implements _i2.UserResponse {
  _FakeUserResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_16 extends _i1.SmartFake implements Object {
  _FakeObject_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionResponse_17 extends _i1.SmartFake
    implements _i2.FunctionResponse {
  _FakeFunctionResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_18 extends _i1.SmartFake implements Duration {
  _FakeDuration_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebSocketChannel_19 extends _i1.SmartFake
    implements _i3.WebSocketChannel {
  _FakeWebSocketChannel_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRetryTimer_20 extends _i1.SmartFake implements _i4.RetryTimer {
  _FakeRetryTimer_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestQueryBuilder_21<T> extends _i1.SmartFake
    implements _i2.PostgrestQueryBuilder<T> {
  _FakePostgrestQueryBuilder_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStreamFilterBuilder_22 extends _i1.SmartFake
    implements _i2.SupabaseStreamFilterBuilder {
  _FakeSupabaseStreamFilterBuilder_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePostgrestBuilder_23<T, S, R> extends _i1.SmartFake
    implements _i2.PostgrestBuilder<T, S, R> {
  _FakePostgrestBuilder_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_24 extends _i1.SmartFake implements Uri {
  _FakeUri_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_25<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestTransformBuilder_26<T1> extends _i1.SmartFake
    implements _i2.PostgrestTransformBuilder<T1> {
  _FakePostgrestTransformBuilder_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponsePostgrestBuilder_27<T1, S, R> extends _i1.SmartFake
    implements _i2.ResponsePostgrestBuilder<T1, S, R> {
  _FakeResponsePostgrestBuilder_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_3(this, Invocation.getter(#rest)),
          )
          as _i2.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_4(this, Invocation.getter(#auth)),
          )
          as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i2.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_9(this, Invocation.getter(#admin)),
          )
          as _i2.GoTrueAdminApi);

  @override
  _i2.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_10(this, Invocation.getter(#mfa)),
          )
          as _i2.GoTrueMFAApi);

  @override
  _i5.Stream<_i2.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Stream<_i2.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i2.GoTrueAdminApi? value) => super.noSuchMethod(
    Invocation.setter(#admin, value),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i2.GoTrueMFAApi? value) => super.noSuchMethod(
    Invocation.setter(#mfa, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i2.OtpChannel? channel = _i2.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.OAuthResponse> getOAuthSignInUrl({
    required _i2.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i5.Future<_i2.OAuthResponse>.value(
              _FakeOAuthResponse_12(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.OAuthResponse>);

  @override
  _i5.Future<_i2.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i5.Future<_i2.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_13(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthSessionUrlResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signInWithIdToken({
    required _i2.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i2.OtpChannel? channel = _i2.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i2.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ResendResponse> resend({
    String? email,
    String? phone,
    required _i2.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<_i2.ResendResponse>.value(
              _FakeResendResponse_14(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ResendResponse>);

  @override
  _i5.Future<_i2.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i5.Future<_i2.UserResponse>.value(
              _FakeUserResponse_15(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i5.Future<_i2.UserResponse>);

  @override
  _i5.Future<_i2.UserResponse> updateUser(
    _i2.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i5.Future<_i2.UserResponse>.value(
              _FakeUserResponse_15(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.UserResponse>);

  @override
  _i5.Future<_i2.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [refreshToken]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i5.Future<_i2.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_13(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AuthSessionUrlResponse>);

  @override
  _i5.Future<void> signOut({
    _i2.SignOutScope? scope = _i2.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i5.Future<List<_i2.UserIdentity>>.value(
              <_i2.UserIdentity>[],
            ),
          )
          as _i5.Future<List<_i2.UserIdentity>>);

  @override
  _i5.Future<_i2.AuthResponse> linkIdentityWithIdToken({
    required _i2.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.OAuthResponse> getLinkIdentityUrl(
    _i2.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i5.Future<_i2.OAuthResponse>.value(
              _FakeOAuthResponse_12(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.OAuthResponse>);

  @override
  _i5.Future<void> unlinkIdentity(_i2.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_11(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i2.AuthChangeEvent? event, {
    _i2.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_16(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);
}

/// A class which mocks [FunctionsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionsClient extends _i1.Mock implements _i2.FunctionsClient {
  MockFunctionsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  void setAuth(String? token) => super.noSuchMethod(
    Invocation.method(#setAuth, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.FunctionResponse> invoke(
    String? functionName, {
    Map<String, String>? headers,
    Object? body,
    Iterable<_i7.MultipartFile>? files,
    Map<String, dynamic>? queryParameters,
    _i2.HttpMethod? method = _i2.HttpMethod.post,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #invoke,
              [functionName],
              {
                #headers: headers,
                #body: body,
                #files: files,
                #queryParameters: queryParameters,
                #method: method,
              },
            ),
            returnValue: _i5.Future<_i2.FunctionResponse>.value(
              _FakeFunctionResponse_17(
                this,
                Invocation.method(
                  #invoke,
                  [functionName],
                  {
                    #headers: headers,
                    #body: body,
                    #files: files,
                    #queryParameters: queryParameters,
                    #method: method,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.FunctionResponse>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [RealtimeClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeClient extends _i1.Mock implements _i2.RealtimeClient {
  MockRealtimeClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.RealtimeChannel> get channels =>
      (super.noSuchMethod(
            Invocation.getter(#channels),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  String get endPoint =>
      (super.noSuchMethod(
            Invocation.getter(#endPoint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#endPoint),
            ),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, dynamic> get params =>
      (super.noSuchMethod(
            Invocation.getter(#params),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_18(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i2.WebSocketTransport get transport =>
      (super.noSuchMethod(
            Invocation.getter(#transport),
            returnValue: (String url, Map<String, String> headers) =>
                _FakeWebSocketChannel_19(this, Invocation.getter(#transport)),
          )
          as _i2.WebSocketTransport);

  @override
  int get heartbeatIntervalMs =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatIntervalMs),
            returnValue: 0,
          )
          as int);

  @override
  int get ref =>
      (super.noSuchMethod(Invocation.getter(#ref), returnValue: 0) as int);

  @override
  _i4.RetryTimer get reconnectTimer =>
      (super.noSuchMethod(
            Invocation.getter(#reconnectTimer),
            returnValue: _FakeRetryTimer_20(
              this,
              Invocation.getter(#reconnectTimer),
            ),
          )
          as _i4.RetryTimer);

  @override
  _i2.RealtimeEncode get encode =>
      (super.noSuchMethod(
            Invocation.getter(#encode),
            returnValue: (dynamic payload, void Function(String) callback) {},
          )
          as _i2.RealtimeEncode);

  @override
  _i2.RealtimeDecode get decode =>
      (super.noSuchMethod(
            Invocation.getter(#decode),
            returnValue: (String payload, void Function(dynamic) callback) {},
          )
          as _i2.RealtimeDecode);

  @override
  _i4.TimerCalculation get reconnectAfterMs =>
      (super.noSuchMethod(
            Invocation.getter(#reconnectAfterMs),
            returnValue: (int tries) => 0,
          )
          as _i4.TimerCalculation);

  @override
  List<dynamic> get sendBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#sendBuffer),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, List<Function>> get stateChangeCallbacks =>
      (super.noSuchMethod(
            Invocation.getter(#stateChangeCallbacks),
            returnValue: <String, List<Function>>{},
          )
          as Map<String, List<Function>>);

  @override
  int get longpollerTimeout =>
      (super.noSuchMethod(Invocation.getter(#longpollerTimeout), returnValue: 0)
          as int);

  @override
  String get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#connectionState),
            ),
          )
          as String);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  String get endPointURL =>
      (super.noSuchMethod(
            Invocation.getter(#endPointURL),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#endPointURL),
            ),
          )
          as String);

  @override
  set accessToken(String? value) => super.noSuchMethod(
    Invocation.setter(#accessToken, value),
    returnValueForMissingStub: null,
  );

  @override
  set channels(List<_i2.RealtimeChannel>? value) => super.noSuchMethod(
    Invocation.setter(#channels, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeatIntervalMs(int? value) => super.noSuchMethod(
    Invocation.setter(#heartbeatIntervalMs, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeatTimer(_i5.Timer? value) => super.noSuchMethod(
    Invocation.setter(#heartbeatTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set pendingHeartbeatRef(String? value) => super.noSuchMethod(
    Invocation.setter(#pendingHeartbeatRef, value),
    returnValueForMissingStub: null,
  );

  @override
  set ref(int? value) => super.noSuchMethod(
    Invocation.setter(#ref, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectTimer(_i4.RetryTimer? value) => super.noSuchMethod(
    Invocation.setter(#reconnectTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set logger(void Function(String?, String?, dynamic)? value) =>
      super.noSuchMethod(
        Invocation.setter(#logger, value),
        returnValueForMissingStub: null,
      );

  @override
  set encode(_i2.RealtimeEncode? value) => super.noSuchMethod(
    Invocation.setter(#encode, value),
    returnValueForMissingStub: null,
  );

  @override
  set decode(_i2.RealtimeDecode? value) => super.noSuchMethod(
    Invocation.setter(#decode, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectAfterMs(_i4.TimerCalculation? value) => super.noSuchMethod(
    Invocation.setter(#reconnectAfterMs, value),
    returnValueForMissingStub: null,
  );

  @override
  set conn(_i3.WebSocketChannel? value) => super.noSuchMethod(
    Invocation.setter(#conn, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#sendBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set stateChangeCallbacks(Map<String, List<Function>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#stateChangeCallbacks, value),
        returnValueForMissingStub: null,
      );

  @override
  set longpollerTimeout(int? value) => super.noSuchMethod(
    Invocation.setter(#longpollerTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set connState(_i2.SocketStates? value) => super.noSuchMethod(
    Invocation.setter(#connState, value),
    returnValueForMissingStub: null,
  );

  @override
  set customAccessToken(_i5.Future<String?> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(#customAccessToken, value),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect({int? code, String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [], {#code: code, #reason: reason}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  void log([
    String? kind,
    String? msg,
    dynamic data,
    _i8.Level? level = _i8.Level.FINEST,
  ]) => super.noSuchMethod(
    Invocation.method(#log, [kind, msg, data, level]),
    returnValueForMissingStub: null,
  );

  @override
  void onOpen(void Function()? callback) => super.noSuchMethod(
    Invocation.method(#onOpen, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onClose(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onClose, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onError, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onMessage(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onMessage, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(_i2.RealtimeChannel? channel) => super.noSuchMethod(
    Invocation.method(#remove, [channel]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RealtimeChannel channel(
    String? topic, [
    _i2.RealtimeChannelConfig? params = const _i2.RealtimeChannelConfig(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [topic, params]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [topic, params]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  String? push(_i9.Message? message) =>
      (super.noSuchMethod(Invocation.method(#push, [message])) as String?);

  @override
  void onConnMessage(String? rawMessage) => super.noSuchMethod(
    Invocation.method(#onConnMessage, [rawMessage]),
    returnValueForMissingStub: null,
  );

  @override
  String makeRef() =>
      (super.noSuchMethod(
            Invocation.method(#makeRef, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#makeRef, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAuth(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAuth, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void leaveOpenTopic(String? topic) => super.noSuchMethod(
    Invocation.method(#leaveOpenTopic, [topic]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> sendHeartbeat() =>
      (super.noSuchMethod(
            Invocation.method(#sendHeartbeat, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PostgrestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestClient extends _i1.Mock implements _i2.PostgrestClient {
  MockPostgrestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.PostgrestClient auth(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#auth, [token]),
            returnValue: _FakePostgrestClient_3(
              this,
              Invocation.method(#auth, [token]),
            ),
          )
          as _i2.PostgrestClient);

  @override
  _i2.PostgrestClient setAuth(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAuth, [token]),
            returnValue: _FakePostgrestClient_3(
              this,
              Invocation.method(#setAuth, [token]),
            ),
          )
          as _i2.PostgrestClient);

  @override
  _i2.PostgrestQueryBuilder<void> from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakePostgrestQueryBuilder_21<void>(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.PostgrestQueryBuilder<void>);

  @override
  _i2.PostgrestClient schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakePostgrestClient_3(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.PostgrestClient);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<dynamic, dynamic>? params,
    bool? get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SupabaseQueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseQueryBuilder extends _i1.Mock
    implements _i2.SupabaseQueryBuilder {
  MockSupabaseQueryBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseStreamFilterBuilder stream({required List<String>? primaryKey}) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            returnValue: _FakeSupabaseStreamFilterBuilder_22(
              this,
              Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            ),
          )
          as _i2.SupabaseStreamFilterBuilder);

  @override
  _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestFilterBuilder_7<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> insert(
    Object? values, {
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [values],
              {#defaultToNull: defaultToNull},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> upsert(
    Object? values, {
    String? onConflict,
    bool? ignoreDuplicates = false,
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [values],
              {
                #onConflict: onConflict,
                #ignoreDuplicates: ignoreDuplicates,
                #defaultToNull: defaultToNull,
              },
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> update(Map<dynamic, dynamic>? values) =>
      (super.noSuchMethod(
            Invocation.method(#update, [values]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<int> count([
    _i2.CountOption? option = _i2.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [option]),
            returnValue: _FakePostgrestFilterBuilder_7<int>(
              this,
              Invocation.method(#count, [option]),
            ),
          )
          as _i2.PostgrestFilterBuilder<int>);

  @override
  _i2.PostgrestQueryBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestQueryBuilder_21<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestQueryBuilder<dynamic>);

  @override
  _i2.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i2.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_23<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i5.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i5.Stream<dynamic>.empty(),
          )
          as _i5.Stream<dynamic>);

  @override
  _i5.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<U> then<U>(
    _i5.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i5.Future<U>.value(v),
                ) ??
                _FakeFuture_25<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i5.Future<U>);

  @override
  _i5.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i5.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> whenComplete(_i5.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}

/// A class which mocks [PostgrestFilterBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestFilterBuilder<T> extends _i1.Mock
    implements _i2.PostgrestFilterBuilder<T> {
  MockPostgrestFilterBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestFilterBuilder<T> copyWithUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithUrl, [url]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#copyWithUrl, [url]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> not(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#not, [column, operator, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#not, [column, operator, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> or(
    String? filters, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #or,
              [filters],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(
                #or,
                [filters],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> eq(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#eq, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#eq, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> neq(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#neq, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#neq, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> gt(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#gt, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#gt, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> gte(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#gte, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#gte, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> lt(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#lt, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#lt, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> lte(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#lte, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#lte, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> like(String? column, String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#like, [column, pattern]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#like, [column, pattern]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> likeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#likeAllOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> likeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#likeAnyOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<T> ilike(String? column, String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#ilike, [column, pattern]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#ilike, [column, pattern]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> ilikeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#ilikeAllOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> ilikeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#ilikeAnyOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<T> isFilter(String? column, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#isFilter, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#isFilter, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> inFilter(
    String? column,
    List<dynamic>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inFilter, [column, values]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#inFilter, [column, values]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> contains(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#contains, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> containedBy(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#containedBy, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#containedBy, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> rangeLt(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLt, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rangeLt, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> rangeGt(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGt, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rangeGt, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> rangeGte(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGte, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rangeGte, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> rangeLte(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLte, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rangeLte, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> rangeAdjacent(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeAdjacent, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rangeAdjacent, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> overlaps(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#overlaps, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#overlaps, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> textSearch(
    String? column,
    String? query, {
    String? config,
    _i2.TextSearchType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #textSearch,
              [column, query],
              {#config: config, #type: type},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(
                #textSearch,
                [column, query],
                {#config: config, #type: type},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> filter(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [column, operator, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#filter, [column, operator, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> match(Map<String, Object>? query) =>
      (super.noSuchMethod(
            Invocation.method(#match, [query]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#match, [query]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestFilterBuilder<T> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestTransformBuilder_26<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestTransformBuilder<T> order(
    String? column, {
    bool? ascending = false,
    bool? nullsFirst = false,
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #order,
              [column],
              {
                #ascending: ascending,
                #nullsFirst: nullsFirst,
                #referencedTable: referencedTable,
              },
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #order,
                [column],
                {
                  #ascending: ascending,
                  #nullsFirst: nullsFirst,
                  #referencedTable: referencedTable,
                },
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<T> limit(
    int? count, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #limit,
              [count],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #limit,
                [count],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<T> range(
    int? from,
    int? to, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #range,
              [from, to],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #range,
                [from, to],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>> single() =>
      (super.noSuchMethod(
            Invocation.method(#single, []),
            returnValue:
                _FakePostgrestTransformBuilder_26<Map<String, dynamic>>(
                  this,
                  Invocation.method(#single, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>?> maybeSingle() =>
      (super.noSuchMethod(
            Invocation.method(#maybeSingle, []),
            returnValue:
                _FakePostgrestTransformBuilder_26<Map<String, dynamic>?>(
                  this,
                  Invocation.method(#maybeSingle, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>?>);

  @override
  _i2.PostgrestTransformBuilder<String> csv() =>
      (super.noSuchMethod(
            Invocation.method(#csv, []),
            returnValue: _FakePostgrestTransformBuilder_26<String>(
              this,
              Invocation.method(#csv, []),
            ),
          )
          as _i2.PostgrestTransformBuilder<String>);

  @override
  _i2.ResponsePostgrestBuilder<_i2.PostgrestResponse<T>, T, T> count([
    _i2.CountOption? count = _i2.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [count]),
            returnValue:
                _FakeResponsePostgrestBuilder_27<
                  _i2.PostgrestResponse<T>,
                  T,
                  T
                >(this, Invocation.method(#count, [count])),
          )
          as _i2.ResponsePostgrestBuilder<_i2.PostgrestResponse<T>, T, T>);

  @override
  _i2.PostgrestBuilder<void, void, void> head() =>
      (super.noSuchMethod(
            Invocation.method(#head, []),
            returnValue: _FakePostgrestBuilder_23<void, void, void>(
              this,
              Invocation.method(#head, []),
            ),
          )
          as _i2.PostgrestBuilder<void, void, void>);

  @override
  _i2.ResponsePostgrestBuilder<
    Map<String, dynamic>,
    Map<String, dynamic>,
    Map<String, dynamic>
  >
  geojson() =>
      (super.noSuchMethod(
            Invocation.method(#geojson, []),
            returnValue:
                _FakeResponsePostgrestBuilder_27<
                  Map<String, dynamic>,
                  Map<String, dynamic>,
                  Map<String, dynamic>
                >(this, Invocation.method(#geojson, [])),
          )
          as _i2.ResponsePostgrestBuilder<
            Map<String, dynamic>,
            Map<String, dynamic>,
            Map<String, dynamic>
          >);

  @override
  _i2.PostgrestBuilder<String, String, String> explain({
    bool? analyze = false,
    bool? verbose = false,
    bool? settings = false,
    bool? buffers = false,
    bool? wal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explain, [], {
              #analyze: analyze,
              #verbose: verbose,
              #settings: settings,
              #buffers: buffers,
              #wal: wal,
            }),
            returnValue: _FakePostgrestBuilder_23<String, String, String>(
              this,
              Invocation.method(#explain, [], {
                #analyze: analyze,
                #verbose: verbose,
                #settings: settings,
                #buffers: buffers,
                #wal: wal,
              }),
            ),
          )
          as _i2.PostgrestBuilder<String, String, String>);

  @override
  _i2.PostgrestBuilder<U, U, T> withConverter<U>(
    _i2.PostgrestConverter<U, T>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_23<U, U, T>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, T>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i5.Stream<T> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  _i5.Future<T> catchError(Function? onError, {bool Function(Object)? test}) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#catchError, [onError], {#test: test}),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(#catchError, [onError], {#test: test}),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<U> then<U>(
    _i5.FutureOr<U> Function(T)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i5.Future<U>.value(v),
                ) ??
                _FakeFuture_25<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i5.Future<U>);

  @override
  _i5.Future<T> timeout(
    Duration? timeLimit, {
    _i5.FutureOr<T> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #timeout,
                      [timeLimit],
                      {#onTimeout: onTimeout},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #timeout,
                    [timeLimit],
                    {#onTimeout: onTimeout},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> whenComplete(_i5.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#whenComplete, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(#whenComplete, [action]),
                ),
          )
          as _i5.Future<T>);
}

/// A class which mocks [PostgrestTransformBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestTransformBuilder<T> extends _i1.Mock
    implements _i2.PostgrestTransformBuilder<T> {
  MockPostgrestTransformBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestTransformBuilder<T> copyWithUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithUrl, [url]),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(#copyWithUrl, [url]),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<T> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestTransformBuilder_26<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestTransformBuilder<T> order(
    String? column, {
    bool? ascending = false,
    bool? nullsFirst = false,
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #order,
              [column],
              {
                #ascending: ascending,
                #nullsFirst: nullsFirst,
                #referencedTable: referencedTable,
              },
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #order,
                [column],
                {
                  #ascending: ascending,
                  #nullsFirst: nullsFirst,
                  #referencedTable: referencedTable,
                },
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<T> limit(
    int? count, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #limit,
              [count],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #limit,
                [count],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<T> range(
    int? from,
    int? to, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #range,
              [from, to],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_26<T>(
              this,
              Invocation.method(
                #range,
                [from, to],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<T>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>> single() =>
      (super.noSuchMethod(
            Invocation.method(#single, []),
            returnValue:
                _FakePostgrestTransformBuilder_26<Map<String, dynamic>>(
                  this,
                  Invocation.method(#single, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>?> maybeSingle() =>
      (super.noSuchMethod(
            Invocation.method(#maybeSingle, []),
            returnValue:
                _FakePostgrestTransformBuilder_26<Map<String, dynamic>?>(
                  this,
                  Invocation.method(#maybeSingle, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>?>);

  @override
  _i2.PostgrestTransformBuilder<String> csv() =>
      (super.noSuchMethod(
            Invocation.method(#csv, []),
            returnValue: _FakePostgrestTransformBuilder_26<String>(
              this,
              Invocation.method(#csv, []),
            ),
          )
          as _i2.PostgrestTransformBuilder<String>);

  @override
  _i2.ResponsePostgrestBuilder<_i2.PostgrestResponse<T>, T, T> count([
    _i2.CountOption? count = _i2.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [count]),
            returnValue:
                _FakeResponsePostgrestBuilder_27<
                  _i2.PostgrestResponse<T>,
                  T,
                  T
                >(this, Invocation.method(#count, [count])),
          )
          as _i2.ResponsePostgrestBuilder<_i2.PostgrestResponse<T>, T, T>);

  @override
  _i2.PostgrestBuilder<void, void, void> head() =>
      (super.noSuchMethod(
            Invocation.method(#head, []),
            returnValue: _FakePostgrestBuilder_23<void, void, void>(
              this,
              Invocation.method(#head, []),
            ),
          )
          as _i2.PostgrestBuilder<void, void, void>);

  @override
  _i2.ResponsePostgrestBuilder<
    Map<String, dynamic>,
    Map<String, dynamic>,
    Map<String, dynamic>
  >
  geojson() =>
      (super.noSuchMethod(
            Invocation.method(#geojson, []),
            returnValue:
                _FakeResponsePostgrestBuilder_27<
                  Map<String, dynamic>,
                  Map<String, dynamic>,
                  Map<String, dynamic>
                >(this, Invocation.method(#geojson, [])),
          )
          as _i2.ResponsePostgrestBuilder<
            Map<String, dynamic>,
            Map<String, dynamic>,
            Map<String, dynamic>
          >);

  @override
  _i2.PostgrestBuilder<String, String, String> explain({
    bool? analyze = false,
    bool? verbose = false,
    bool? settings = false,
    bool? buffers = false,
    bool? wal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explain, [], {
              #analyze: analyze,
              #verbose: verbose,
              #settings: settings,
              #buffers: buffers,
              #wal: wal,
            }),
            returnValue: _FakePostgrestBuilder_23<String, String, String>(
              this,
              Invocation.method(#explain, [], {
                #analyze: analyze,
                #verbose: verbose,
                #settings: settings,
                #buffers: buffers,
                #wal: wal,
              }),
            ),
          )
          as _i2.PostgrestBuilder<String, String, String>);

  @override
  _i2.PostgrestBuilder<U, U, T> withConverter<U>(
    _i2.PostgrestConverter<U, T>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_23<U, U, T>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, T>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_24(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i5.Stream<T> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  _i5.Future<T> catchError(Function? onError, {bool Function(Object)? test}) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#catchError, [onError], {#test: test}),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(#catchError, [onError], {#test: test}),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<U> then<U>(
    _i5.FutureOr<U> Function(T)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i5.Future<U>.value(v),
                ) ??
                _FakeFuture_25<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i5.Future<U>);

  @override
  _i5.Future<T> timeout(
    Duration? timeLimit, {
    _i5.FutureOr<T> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #timeout,
                      [timeLimit],
                      {#onTimeout: onTimeout},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(
                    #timeout,
                    [timeLimit],
                    {#onTimeout: onTimeout},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> whenComplete(_i5.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#whenComplete, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_25<T>(
                  this,
                  Invocation.method(#whenComplete, [action]),
                ),
          )
          as _i5.Future<T>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i10.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i11.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i12.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> logEvent(String? type, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [type, message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasValidLocalSession() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidLocalSession, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getSessionData() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionData, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getUserPhone() =>
      (super.noSuchMethod(
            Invocation.method(#getUserPhone, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getUserRole() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> synchronizeSessions() =>
      (super.noSuchMethod(
            Invocation.method(#synchronizeSessions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool handleStartBackGesture(_i13.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i13.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> didPushRouteInformation(
    _i14.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i12.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i12.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i12.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i5.Future<_i12.AppExitResponse>.value(
              _i12.AppExitResponse.exit,
            ),
          )
          as _i5.Future<_i12.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
